eb:dev:
    image: ruby
    stage: deploy
    environment: live
    script:
       - apt-get update && apt-get install -y zip
       - apt-get install default-jdk -y
       - apt-get install maven -y
       - mvn clean install
       - gem install dpl
       - zip -r deploy.zip ./target/spring-oauth-aws-travis-1.0.0.jar
       - dpl --provider=elasticbeanstalk --zip_file=deploy.zip --skip_cleanup --app="spring-oauth2" --env="SpringOauth2-env" --region="us-east-2" --bucket-name="elasticbeanstalk-us-east-2-793313146116"
    only:
       - master
    artifacts:
       paths:
           - ./
        