language: java
jdk:
  - oraclejdk11
cache:
  directories:
  - $HOME/.m2
before_install:
  - sudo apt-get update 
install:
  - mvn install -B -V
script:
  - mvn test
deploy:
  on:
    branch: master
notifications:
  email: false