language: java
jdk:
  - oraclejdk11
install: true
script:
  - echo "Maven Package"
  - ./mvnw clean install
  - echo "Terminou build Maven"
deploy:
  on:
    branch: master
notifications:
  email: false