language: java
jdk:
  - oraclejdk11
cache:
  directories:
  - $HOME/.m2
install:
  - mvn clean package -B -V
deploy:
  provider: elasticbeanstalk
  skip_cleanup: "true"
  app: "Spring-OAuth2"
  env: "SpringOauth2-env"
  zip_file: target/app-spring-oauth2-aws-travis-1.0.0.jar
  bucket_name: "elasticbeanstalk-us-east-1-793313146116"
  region: "us-east-1"
  access_key_id: 
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  on:
    branch: master
notifications:
  email: "false"