language: java
jdk:
  - oraclejdk11
cache:
  directories:
  - $HOME/.m2
before_install:
  - sudo apt-get update 
install:
  - mvn install -B -V
deploy:
  provider: script
  script: 
    - echo "Aqui AWS......";
  on:
    branch: master
notifications:
  email: false