language: java
jdk:
  - oraclejdk11
cache:
  directories:
  - $HOME/.m2
install:
  - mvn clean package -B -V
script:
   - gem install dpl
   - zip -r deploy.zip ./target/app-spring-oauth2-aws-travis-1.0.0.jar
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"  
  env: "SpringOauth2-env"
  app: "Spring-OAuth2"
  bucket_name: "$AWS_S3_BUCKET"
  zip_file: deploy.zip
  on:
    branch: master
notifications:
  email: false