language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
install:
  - mvn clean package -B -V
deploy:
  provider: script
  script: 
    - echo "Aqui AWS......";
  on:
    branch: master
notifications:
  email: false